#!/usr/bin/env bash

# Created by:       VPR
# Created:          March 29th, 2026

# Updated by:       VPR
# Updated:          March 29th, 2026



################################################################################
#         Common functions, variables, and aliases that I like to use.
################################################################################



function mkcd {
  mkdir "${@}" && cd "${@}"
}

function wclip {
  [[ -x $(which clip.exe) ]] && `which clip.exe`
}

function gen-cf {
  local OPTIND opt

  local TARGET="x86_64-pc-linux"
  local STANDARD="c++26"
  local WARNINGS=1
  local OUTFILE="" # compile_flags.txt
  local EXTRAFLAGS=""

  local USAGE="Usage:
  gen-cf [-t target] [-s standard] [-e extra_flags] [-o outfile] [-w] [-h]

Options:
  -t target       Target triple
  -s standard     C++ standard (example: c++20, c++23)
  -e extra_flags  Extra flags to append
  -o outfile      Output file
  -w              Disable warning flags
  -h              Show this help
"

  while getopts ":e:s:t:wo:h" opt
  do
    case "$opt" in
      e)
        EXTRAFLAGS="${EXTRAFLAGS} ${OPTARG}"
        ;;
      s)
        STANDARD="${OPTARG}"
        ;;
      t)
        TARGET="${OPTARG}"
        ;;
      w)
        WARNINGS=0
        ;;
      o)
        OUTFILE="${OPTARG}"
        ;;
      h)
        printf '%s' "${USAGE}"
        return 0
        ;;
      :)
        printf 'gen-wcpp: option -%s requires an argument\n' "${OPTARG}" >&2
        return 1
        ;;
      \?)
        printf 'gen-wcpp: invalid option -- %s\n' "${OPTARG}" >&2
        printf '%s' "${USAGE}" >&2
        return 1
        ;;
    esac
  done
  shift $((OPTIND - 1))

  local FLAGS=""
  FLAGS+="--target=${TARGET}"$'\n'
  FLAGS+="-std=${STANDARD}"$'\n'

  if (( WARNINGS )); then
    FLAGS+="-Wall"$'\n'
    FLAGS+="-Wextra"$'\n'
    FLAGS+="-Werror"$'\n'
    FLAGS+="-Wshadow"$'\n'
    FLAGS+="-Wpedantic"$'\n'
    FLAGS+="-Wconversion"$'\n'
    FLAGS+="-Woverflow"$'\n'
    FLAGS+="-Wunderflow"$'\n'
  fi

  if [[ -n "${EXTRAFLAGS}" ]]; then
    local extra_flag
    for extra_flag in ${EXTRAFLAGS}
    do
      FLAGS+="${extra_flag}"$'\n'
    done
  fi

  printf '%s' "${FLAGS}"
  if [[ "${OUTFILE}" != "" ]] && [[ ! -e "${OUTFILE}" ]]; then
    printf '%s' "${FLAGS}" > "${OUTFILE}" 
  fi
}

function gen-make {
  local OPTIND opt

  local PROJECT=""

  local CC="gcc"
  local CFLAGS="-std=c99 -O2 -Wall -Wextra -Werror -Wshadow -Wpedantic -Wconversion"

  local LD="ld"
  local LDFLAGS=""

  local BIN="bin"
  local SOURCE="src"
  local OBJECT="build"
  local BUILD='$(OBJECT)'
  local INCLUDE="include"

  local EXT="c"
  local OUTFILE="" # Makefile

  local -a EXTRA_CFLAGS=()
  local -a EXTRA_LDFLAGS=()

  local USAGE="Usage:
  gen-make [-p project] [-c compiler] [-f cflag]... [-l linker] [-r ldflag]...
           [-b bin_dir] [-s src_dir] [-o obj_dir] [-i include_dir]
           [-x extension] [-O outfile] [-h]

Options:
  -p project       Project name
  -c compiler      Compiler
  -f cflag         Extra CFLAG to append (repeatable)
  -l linker        Linker
  -r ldflag        Extra LDFLAG to append (repeatable)
  -b bin_dir       Binary output directory
  -s src_dir       Source directory
  -o obj_dir       Object/build directory
  -i include_dir   Include directory
  -x extension     Source extension (example: c, cpp)
  -O outfile       Output makefile path
  -h               Show this help
"

  while getopts ":p:c:f:l:r:b:s:o:i:x:O:h" opt
  do
    case "$opt" in
      p)
        PROJECT="${OPTARG}"
        ;;
      c)
        CC="${OPTARG}"
        ;;
      f)
        EXTRA_CFLAGS+=("${OPTARG}")
        ;;
      l)
        LD="${OPTARG}"
        ;;
      r)
        EXTRA_LDFLAGS+=("${OPTARG}")
        ;;
      b)
        BIN="${OPTARG}"
        ;;
      s)
        SOURCE="${OPTARG}"
        ;;
      o)
        OBJECT="${OPTARG}"
        ;;
      i)
        INCLUDE="${OPTARG}"
        ;;
      x)
        EXT="${OPTARG}"
        ;;
      O)
        OUTFILE="${OPTARG}"
        ;;
      h)
        printf '%s' "${USAGE}"
        return 0
        ;;
      :)
        printf 'gen-make: option -%s requires an argument\n' "${OPTARG}" >&2
        return 1
        ;;
      \?)
        printf 'gen-make: invalid option -- %s\n%s' "${OPTARG}" >&2
        printf '%s' "${USAGE}" >&2
        return 1
        ;;
    esac
  done
  shift $((OPTIND - 1))

  if [[ ${PROJECT} == "" ]]; then
    printf "Error: -p project is REQUIRED.\n\n%s" "${USAGE}" >&2
    return 1
  fi

  local extra_flag
  for extra_flag in "${EXTRA_CFLAGS[@]}"
  do
    CFLAGS="${CFLAGS} ${extra_flag}"
  done

  for extra_flag in "${EXTRA_LDFLAGS[@]}"
  do
    LDFLAGS="${LDFLAGS} ${extra_flag}"
  done

  local MAKEFILE_CONTENT=""
  MAKEFILE_CONTENT+="PROJECT  = ${PROJECT}"$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+="CC       = ${CC}"$'\n'
  MAKEFILE_CONTENT+="CFLAGS   = ${CFLAGS}"$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+="LD       = ${LD}"$'\n'
  MAKEFILE_CONTENT+="LDFLAGS  = ${LDFLAGS}"$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+="BIN      = ${BIN}"$'\n'
  MAKEFILE_CONTENT+="SOURCE   = ${SOURCE}"$'\n'
  MAKEFILE_CONTENT+="OBJECT   = ${OBJECT}"$'\n'
  MAKEFILE_CONTENT+='BUILD    = $(OBJECT)'$'\n'
  MAKEFILE_CONTENT+="SOURCES  = \$(wildcard \$(SOURCE)/*.${EXT})"$'\n'
  MAKEFILE_CONTENT+="OBJECTS  = \$(patsubst \$(SOURCE)/%.${EXT}, \$(OBJECT)/%.o, \$(SOURCES))"$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+="INCLUDE  = ${INCLUDE}"$'\n'
  MAKEFILE_CONTENT+='INCLUDES = $(addprefix -I,$(INCLUDE))'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='.PHONY: all clean extra-clean $(BIN) $(OBJECT) $(BUILD)\n'
  MAKEFILE_CONTENT+='all: $(PROJECT)'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='$(PROJECT): $(BIN) $(BUILD) $(OBJECTS)'$'\n'
  MAKEFILE_CONTENT+=$'\t''$(LD) $(OBJECTS) $(LDFLAGS) -o $(BIN)/$(PROJECT)'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+="\$(OBJECTS): \$(OBJECT)/%.o : \$(SOURCE)/%.${EXT}"$'\n'
  MAKEFILE_CONTENT+=$'\t''$(CC) $(CFLAGS) $(INCLUDES) -c $^ -o $@'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='$(BIN):'$'\n'
  MAKEFILE_CONTENT+=$'\t''mkdir -p $@'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='$(BUILD):'$'\n'
  MAKEFILE_CONTENT+=$'\t''mkdir -p $@'$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='clean:'$'\n'
  MAKEFILE_CONTENT+=$'\t'"rm -fr ./${BIN}/*"$'\n'
  MAKEFILE_CONTENT+=$'\t'"rm -fr ./${OBJECT}/*"$'\n'
  MAKEFILE_CONTENT+=$'\n'
  MAKEFILE_CONTENT+='extra-clean:'$'\n'
  MAKEFILE_CONTENT+=$'\t'"rm -fr ./${BIN}"$'\n'
  MAKEFILE_CONTENT+=$'\t'"rm -fr ./${OBJECT}"$'\n'

  printf '%s' "${MAKEFILE_CONTENT}"
  if [[ "${OUTFILE}" != "" ]] && [[ ! -e "${OUTFILE}" ]]; then
    printf '%s' "${MAKEFILE_CONTENT}" > "${OUTFILE}"
  fi
}
